name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: chmod 777 ./gradlew && ./gradlew :app:assembleRelease && find app/build/outputs
    - name: Upload apk
      uses: actions/upload-artifact@v1
      with:
        name: app-armeabi-v7a-release-unsigned.apk
        path: app/build/outputs/apk/common/release/app-common-armeabi-v7a-release-unsigned.apk

